# The purpose of this code is to process the data from the raw data of year 2013 and combine with the processed data 2015. 
# Then generate two balance datasets, 1st balance dataset with Diabetes_01 is for binary classification purpose, 2nd balance dataset with Diabetes_012 is for multi-classification purpose.

In [1]:
#imports
import os
import pandas as pd
import numpy as np
import random
random.seed(1)

In [2]:
# read from raw data
dbt_data = pd.read_csv('./brfss2013.csv',encoding='ISO-8859-1')

/home/xavior/anaconda3/envs/project36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (11,14,50,53,102,103,104,105,108,111,112,113,118,119,120,121,122,123,125,126,127,130,132,134,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,177,178,179,180,181,182,183,184,185,186,187,188,190,191,192,193,194,195,197,199,200,201,202,203,204,205,206,207,208,209,210,211,212,216,226,227,228,229,230,312) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
pd.set_option('display.max_columns', 500)
dbt_data.head()

,X_state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,X_psu,ctelenum,pvtresd1,colghous,stateres,cellfon3,ladult,numadult,nummen,numwomen,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,sleptim1,bphigh4,bpmeds,bloodcho,cholchk,toldhi2,cvdinfr4,cvdcrhd4,cvdstrk3,asthma3,asthnow,chcscncr,chcocncr,chccopd1,havarth3,addepev2,chckidny,diabete3,veteran3,marital,children,educa,employ1,income2,weight2,height3,numhhol2,numphon2,cpdemo1,cpdemo4,internet,renthom1,sex,pregnant,qlactlm2,useequip,blind,decide,diffwalk,diffdres,diffalon,smoke100,smokday2,stopsmk2,lastsmk2,usenow3,alcday5,avedrnk2,drnk3ge5,maxdrnks,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exerany2,exract11,exeroft1,exerhmm1,exract21,exeroft2,exerhmm2,strength,lmtjoin3,arthdis2,arthsocl,joinpain,seatbelt,flushot6,flshtmy2,tetanus,pneuvac3,hivtst6,hivtstd3,whrtst10,pdiabtst,prediab1,diabage2,insulin,bldsugar,feetchk2,doctdiab,chkhemo3,feetchk,eyeexam,diabeye,diabedu,painact2,qlmentl2,qlstres2,qlhlth2,medicare,hlthcvrg,delaymed,dlyother,nocov121,lstcovrg,drvisits,medscost,carercvd,medbills,ssbsugar,ssbfrut2,wtchsalt,longwtch,dradvise,asthmage,asattack,aservist,asdrvist,asrchkup,asactlim,asymptom,asnoslep,asthmed3,asinhalr,harehab1,strehab1,cvdasprn,aspunsaf,rlivpain,rduchart,rducstrk,arttoday,arthwgt,arthexer,arthedu,imfvplac,hpvadvc2,hpvadsht,hadmam,howlong,profexam,lengexam,hadpap2,lastpap2,hadhyst2,bldstool,lstblds3,hadsigm3,hadsgco1,lastsig3,pcpsaad2,pcpsadi1,pcpsare1,psatest1,psatime,pcpsars1,pcpsade1,pcdmdecn,rrclass2,rrcognt2,rratwrk2,rrhcare3,rrphysm2,rremtsm2,misnervs,mishopls,misrstls,misdeprd,miseffrt,miswtles,misnowrk,mistmnt,mistrhlp,misphlpf,scntmony,scntmeal,scntpaid,scntwrk1,scntlpad,scntlwk1,scntvot1,rcsgendr,rcsrltn2,casthdx2,casthno2,emtsuprt,lsatisfy,ctelnum1,cellfon2,cadult,pvtresd2,cclghous,cstate,landline,pctcell,qstver,qstlang,mscode,X_ststr,X_strwt,X_rawrake,X_wt2rake,X_imprace,X_impnph,X_impeduc,X_impmrtl,X_imphome,X_chispnc,X_crace1,X_impcage,X_impcrac,X_impcsex,X_cllcpwt,X_dualuse,X_dualcor,X_llcpwt2,X_llcpwt,X_rfhlth,X_hcvu651,X_rfhype5,X_cholchk,X_rfchol,X_ltasth1,X_casthm1,X_asthms1,X_drdxar1,X_prace1,X_mrace1,X_hispanc,X_race,X_raceg21,X_racegr3,X_race_g1,X_ageg5yr,X_age65yr,X_age_g,htin4,htm4,wtkg3,X_bmi5,X_bmi5cat,X_rfbmi5,X_chldcnt,X_educag,X_incomg,X_smoker3,X_rfsmok3,drnkany5,drocdy3_,X_rfbing5,X_drnkdy4,X_drnkmo4,X_rfdrhv4,X_rfdrmn4,X_rfdrwm4,ftjuda1_,frutda1_,beanday_,grenday_,orngday_,vegeda1_,X_misfrtn,X_misvegn,X_frtresp,X_vegresp,X_frutsum,X_vegesum,X_frtlt1,X_veglt1,X_frt16,X_veg23,X_fruitex,X_vegetex,X_totinda,metvl11_,metvl21_,maxvo2_,fc60_,actin11_,actin21_,padur1_,padur2_,pafreq1_,pafreq2_,X_minac11,X_minac21,strfreq_,pamiss1_,pamin11_,pamin21_,pa1min_,pavig11_,pavig21_,pa1vigm_,X_pacat1,X_paindx1,X_pa150r2,X_pa300r2,X_pa30021,X_pastrng,X_parec1,X_pastae1,X_lmtact1,X_lmtwrk1,X_lmtscl1,X_rfseat2,X_rfseat3,X_flshot6,X_pneumo2,X_aidtst3,X_age80
0,Alabama,January,1092013.0,January,9.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,Yes,Yes,NaN,Yes,Not a cellular phone,NaN,2.0,1.0,1.0,Fair,30.0,29.0,30.0,Yes,"Yes, only one",No,Within past year,NaN,Yes,Yes,Yes,Within past year,Yes,No,NaN,No,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,Divorced,0.0,College 4 years or more (College graduate),Retired,"Less than $75,000",250,507.0,Yes,2 residential telephone numbers,Yes,10.0,Yes,Own,Female,NaN,Yes,Yes,No,No,Yes,No,Yes,Yes,Not at all,NaN,10 years or more,Not at all,201.0,2.0,0.0,2.0,304.0,104.0,303.0,310.0,303.0,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Yes,Yes,A lot,7.0,Always,No,NaN,"No, did not receive any tetanus since 2005",Yes,No,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,30.0,30.0,0.0,Yes,3 7,You didn't have transportation,NaN,No,NaN,5.0,No,Very satisfied,No,305.0,305.0,Yes,408.0,Yes,56.0,Yes,0.0,0.0,3.0,NaN,"Every day, but not all the time",None,1 to 14 days,5 to 14 times,NaN,NaN,No,"Yes, stomach problems",NaN,NaN,NaN,I can do some things I would like to do,Yes,Yes,No,NaN,NaN,NaN,Yes,Within past 2 years,Yes,Within past 2 years,Yes,5 or more years ago,Yes,No,NaN,Yes,Colonoscopy,Within past 2 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Black or African American,Never,NaN,The same as other races,No,No,Some,Some,Some,None,All,None,30.0,Yes,Agree strongly,Disagree slightly,Never,Never,NaN,NaN,Paid by salary,NaN,Yes,NaN,NaN,NaN,NaN,Always,Very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Only Version Landline,English,Inside a suburban county of the MSA,11081.0,40.197675,1.0,40.197675,"Black, Non-Hispanic",2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Dual Phone Use,NaN,331.493357,238.016092,Fair or Poor Health,Have health care coverage,Yes,Had cholesterol checked in past 5 years,Yes,Yes,Yes,Current,Diagnosed with arthritis,Black or African American,Black or African American,"Not of Hispanic, Latino/a, or Spanish origin","Black only, non-Hispanic",Non-White or Hispanic,"Black only, Non-Hispanic",Black - Non-Hispanic,Age 60 to 64,Age 18 to 64,Age 55 to 64,67.0,170.0,11340.0,3916.0,Obese,Yes,No children in household,Graduated from college or technical school,"$50,000 or more",Former smoker,No,No,3.0,No,7.0,2.0,No,NaN,No,13.0,400.0,10.0,33.0,10.0,NaN,No missing fruit responses,1 missing response,Included - Missing Fruit Responses,Not Included - Missing Fruit Responses,413.0,53.0,Consumed fruit one or more times per day,Consumed vegetables less than one time per day,Included - values are in accepted range,Included - values are in accepted range,No missing values and in accepted range,Missing vegetables responses,No physical activity or exercise in last 30 days,NaN,NaN,2580.0,442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Inactive,Did not meet aerobic recommendations,0 minutes,0 minutes,0-300 minutes,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Told have arthritis and have limited usual act...,Told have arthritis and have limited work,Told have arthritis and social activities limi...,Always or almost always wear seat belt,Always wear seat belt,NaN,NaN,No,60.0
1,Alabama,January,1192013.0,January,19.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,Yes,Yes,NaN,Yes,Not a cellular phone,NaN,2.0,1.0,1.0,Good,0.0,0.0,NaN,Yes,"Yes, only one",No,Within past year,6.0,No,NaN,Yes,Within past year,No,No,No,No,No,NaN,No,No,No,No,Yes,No,No,No,Married,2.0,College 1 year to 3 years (Some college or tec...,Employed for wages,"$75,000 or more",127,510.0,No,NaN,Yes,70.0,Yes,Own,Female,NaN,No,No,No,No,No,No,No,No,NaN,NaN,NaN,Not at all,0.0,NaN,NaN,NaN,305.0,301.0,310.0,203.0,202.0,203.0,Yes,Walking,105.0,20.0,"Household Activities (vacuuming, dusting, home...",101.0,10.0,0.0,NaN,NaN,NaN,NaN,Always,Yes,October 2012,"Yes, received Tdap",No,Yes,NaN,Private doctor or HMO,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,3.0,25.0,No,2,"No, I did not delay getting medical care",NaN,No,NaN,3.0,No,Very satisfied,No,203.0,0.0,No,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Workplace,NaN,NaN,Yes,Within past 3 years,Yes,Within past 3 years,Yes,Within past 3 years,No,No,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,Never,The same as other races,The same as other races,No,No,A little,None,None,None,None,None,0.0,No,Agree slightly,Disagree slightly,Never,Never,Paid by the hour,35.0,NaN,NaN,Yes,Girl,Parent,No,NaN,Sometimes,Satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Only Version Landline,English,Inside a suburban county of the MSA,11081.0,40.197675,2.0,80.395350,"White, Non-Hispanic",1.0,NaN,NaN,NaN,"Child not of Hispanic, Latino/a, or Spanish or...",White,10-14 Years old,"White, non-Hispanic",Female,954.078239,No Dual Phone Use,NaN,662.986714,737.694204,Good or Better Health,Have health care coverage,No,Had cholesterol checked in past 5 years,No,No,No,Never,Not diagnosed with arthritis,White,White,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic",White - Non-Hispanic,Age 50 to 54,Age 18 to 64,Age 45 to 54,70.0,178.0,5761.0,1822.0,Underweight,No,Two children in household,Attended college or technical school,"$50,000 or more",Never smoked,No,Yes,0.0,No,0.0,0.0,No,NaN,No,17.0,3.0,33.0,43.0,29.0,43.0,No missing fruit responses,No missing vegetable responses,Included - Missing Fruit Responses,Included - Missing Fruit Responses,20.0,148.0,Consumed fruit less than one time per day,Consumed vegetables one or more times per day,Included - values are in accepted range,Included - values are in accepted range,No missing values and in accepted range,No missing values and in accepted range,Had physical activity or exercise,35.0,33.0,2950.0,506.0,Moderate,Moderate,20.0,10.0,5000.0,1000.0,100.0,10.0,0.0,0.0,100.0,10.0,110.0,0.0,0.0,0,Insufficiently active,Did not meet aerobic recommendations,1-149 minutes,1-300 minutes,0-300 minutes,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Not told they have arthritis,Not told they have arthritis,Not told they have arthritis,Always or almost always wear seat belt,Always wear seat belt,NaN,NaN,Yes,50.0
2,Alabama,January,1192013.0,January,19.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,Yes,Yes,NaN,Yes,Not a cellular phone,NaN,3.0,2.0,1.0,Good,3.0,2.0,0.0,Yes,"Yes, only one",No,Within past year,9.0,No,NaN,Yes,5 or more years ago,No,No,No,No,No,NaN,No,No,No,Yes,Yes,No,No,No,Married,0.0,College 4 years or more (College graduate),Employed for wages,"$75,000 or more",160,504.0,No,NaN,Yes,70.0,Yes,Own,Female,NaN,Yes,No,No,No,Yes,No,No,Yes,Some days,Yes,NaN,Not at all,220.0,4.0,20.0,10.0,301.0,203.0,202.0,202.0,310.0,330.0,No,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Yes,Yes,A little,5.0,Always,Yes,January 2013,"Yes, received Tdap",No,Yes,NaN,At home,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,2.0,5.0,2.0,No,3,NaN,NaN,No,NaN,6.0,No,Very satisfied,No,202.0,308.0,No,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,NaN,NaN,NaN,I can do some things I would like to do,No,Yes,No,A doctor´s office or health maintenance organi...,NaN,NaN,Yes,Within past year,Yes,Within past year,Yes,Within past year,Yes,Yes,5 or more years ago,Yes,Colonoscopy,Within past 3 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,Never,The same as other races,The same as other races,No,No,None,None,None,None,None,None,0.0,No,Agree strongly,Agree strongly,Never,Never,Paid by the hour,40.0,NaN,NaN,Yes,NaN,NaN,NaN,NaN,Usually,Very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Only Version Landline,English,Inside a suburban county of the MSA,11081.0,40.197675,3.0,120.593025,"White, Non-Hispanic",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Dual Phone Use,NaN,994.480071,568.527386,Good or Better Health,Have health care coverage,No,Did not have cholesterol checked in past 5 years,No,No,No,Never,Diagnosed with arthritis,White,White,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic",White - Non-Hispanic,Age 55 to 59,Age 18 to 64,Age 55 to 64,64.0,163.0,7257.0,2746.0,Overweight,Yes,No children in household,Graduated from college or technical school,"$50,000 or more",Current smoker - now smokes some days,Yes,No,67.0,Yes,267.0,80.0,Yes,NaN,Yes,3.0,43.0,29.0,29.0,33.0,100.0,No missing fruit responses,No missing vegetable responses,Included - Missing Fruit Responses,Included - Missing Fruit Responses,46.0,191.0,Consumed fruit less than one time per day,Consumed vegetables one or more times per day,Included - values are in accepted range,Included - values are in accepted range,No missing values and in accepted range,No missing values and in accepted range,No physical activity or exercise in last 30 days,NaN,NaN,2765.0,474.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Inactive,Did not meet aerobic recommendations,0 minutes,0 minutes,0-300 minutes,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Told have arthritis and have limited usual act...,Told have arthritis and have limited work,Told have arthritis and social activities limi...,Always or almost always wear seat belt,Always wear seat belt,NaN,NaN,Yes,55.0
3,Alabama,January,1112013.0,January,11.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,Yes,Yes,NaN,Yes,Not a cellular phone,NaN,2.0,1.0,1.0,Very good,2.0,0.0,0.0,Yes,"Yes, only one",No,Within past 2 years,8.0,No,NaN,Yes,Within past year,Yes,No,No,No,No,NaN,No,No,No,No,No,No,No,No,Married,0.0,Grade 12 or GED (High school graduate),Retired,"Less than $75,000",128,504.0,No,NaN,Yes,75.0,Yes,Own,Female,NaN,No,No,No,No,No,No,No,No,NaN,NaN,NaN,Not at all,208.0,2.0,0.0,2.0,202.0,306.0,202.0,310.0,305.0,204.0,Yes,Walking,205.0,30.0,No other activity,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Always,No,NaN,"No, did not receive any tetanus since 2005",No,No,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,6.0,4.0,20.0,No,3,"No, I did not delay getting medical care",NaN,No,NaN,1.0,No,Somewhat satisfied,No,203.0,315.0,Yes,405.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Within past year,Yes,Within past 2 years,Yes,Within past 2 years,No,Yes,5 or more years ago,Yes,Colonoscopy,Within past 5 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,The same as other races,No,No,A little,None,Some,None,None,None,0.0,No,Agree strongly,Disagree slightly,Never,Never,NaN,NaN,Paid by salary,60.0,Yes,NaN,NaN,NaN,NaN,Usually,Very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Only Version Landline,English,Inside a suburban county of the MSA,11081.0,40.197675,2.0,80.395350,"White, Non-Hispanic",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Dual Phone Use,NaN,662.986714,606.976365,Good or Better Health,Have health care coverage,No,Had cholesterol checked in past 5 years,Yes,No,No,Never,Not diagnosed with arthritis,White,White,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic",White - Non-Hispanic,Age 60 to 64,Age 18 to 64,Age 55 to 64,64.0,163.0,5806.0,2197.0,Normal weight,No,No children in household,Graduated high school,"$50,000 or more",Never smoked,No,No,27.0,No,53.0,16.0,No,NaN,No,29.0,20.0,29.0,33.0,17.0,57.0,No missing fruit responses,No missing vegetable responses,Included - Missing Fruit Responses,Included - Missing Fruit Responses,49.0,136.0,Consumed fruit less than one time per day,Consumed vegetables one or more times per day,Included - values are in accepted range,Included - values are in accepted range,No missing values and in accepted range,No missing values and in accepted range,Had physical activity or exercise,35.0,0.0,2432.0,417.0,Moderate,Not Moderate or Vigorous or No Activity,30.0,NaN,1167.0,NaN,35.0,0.0,0.0,0.0,35.0,0.0,35.0,0.0,0.0,0,Insufficiently active,Did not meet aerobic recommendations,1-149 minutes,1-300 minutes,0-300 minutes,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Not told they have arthritis,Not told they have arthritis,Not told they have arthritis,Always or almost always wear seat belt,Always wear seat belt,NaN,NaN,No,64.0
4,Alabama,February,2062013.0,February,6.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,Yes,Yes,NaN,Yes,Not a cellular phone,NaN,2.0,1.0,1.0,Good,10.0,2.0,0.0,Yes,"Yes, only one",No,5 or more years ago,6.0,Yes,No,Yes,Within past 2 years,No,No,No,No,Yes,No,No,Yes,No,No,No,No,No,No,Married,0.0,College 4 years or more (College graduate),Retired,"Less than $50,000",265,600.0,No,NaN,Yes,0.0,Yes,Own,Male,NaN,No,No,No,No,No,No,No,Yes,Not at all,NaN,Within the past month,Not at all,210.0,2.0,0.0,3.0,0.0,302.0,101.0,310.0,303.0,101.0,No,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Always,No,NaN,"No, did not receive any tetanus since 2005",No,No,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,4 2,"No, I did not delay getting medical care",NaN,No,NaN,2.0,No,Very satisfied,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Yes,Colonoscopy,Within past 2 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Never,Never,NaN,NaN,Paid by the job / task,60.0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Only Version Landline,English,Inside a suburban county of the MSA,11082.0,60.319184,2.0,120.638368,"White, Non-Hispanic",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Dual Phone Use,NaN,994.853994,629.847064,Good or Better Health,NaN,Yes,Had cholesterol checked in past 5 years,No,Yes,No,Former,Not diagnosed with arthritis,White,White,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic",White - Non-Hispanic,Age 65 to 69,Age 65 or older,Age 65 or older,72.0,183.0,12020.0,3594.0,Obese,Yes,No children in household,Graduated from college or technical school,"$35,000 to less than $50,000",Former smoker,No,No,33.0,No,67.0,20.0,No,No,NaN,0.0,7.0,100.0,33.0,10.0,100.0,No missing fruit responses,No missing vegetable responses,Included - Missing Fruit Responses,Included - Missing Fruit Responses,7.0,243.0,Consumed fruit less than one time per day,Consumed vegetables one or more times per day,Included - values are in accepted range,Included - values are in accepted range,No missing values and in accepted range,No missing values and in accepted range,No physical activity or exercise in last 30 days,NaN,NaN,2370.0,406.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Inactive,Did not meet aerobic recommendations,0 minutes,0 minutes,0-300 minutes,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Not told they have arthritis,Not told they have arthritis,Not told they have arthritis,Always or almost always wear seat belt,Always wear seat belt,No,No,No,66.0

In [4]:
# select specific columns
brfss_df_selected = dbt_data[['diabete3',
                                         'X_rfhype5',  
                                         'toldhi2', 'X_cholchk', 
                                         'X_bmi5', 
                                         'smoke100', 
                                         'cvdstrk3', 'cvdinfr4', 
                                         'X_totinda', 
                                         'X_frtlt1', 'X_veglt1', 
                                         'X_rfdrhv4', 
                                         'hlthpln1', 'medcost', 
                                         'genhlth', 'menthlth', 'physhlth', 'diffwalk', 
                                         'sex', 'X_ageg5yr', 'educa', 'income2' ]]

In [5]:
brfss_df_selected.shape

(491775, 22)

In [6]:
#rename the selected features
brfss = brfss_df_selected.rename(columns = {'diabete3':'Diabetes_012', 
                                         'X_rfhype5':'HighBP',  
                                         'toldhi2':'HighChol', 'X_cholchk':'CholCheck', 
                                         'X_bmi5':'BMI', 
                                         'smoke100':'Smoker', 
                                         'cvdstrk3':'Stroke', 'cvdinfr4':'HeartDiseaseorAttack', 
                                         'X_totinda':'PhysActivity', 
                                         'X_frtlt1':'Fruits', 'X_veglt1':"Veggies", 
                                         'X_rfdrhv4':'HvyAlcoholConsump', 
                                         'hlthpln1':'AnyHealthcare', 'medcost':'NoDocbcCost', 
                                         'genhlth':'GenHlth', 'menthlth':'MentHlth', 'physhlth':'PhysHlth', 'diffwalk':'DiffWalk', 
                                         'sex':'Sex', 'X_ageg5yr':'Age', 'educa':'Education', 'income2':'Income' })

In [7]:
brfss.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Had cholesterol checked in past 5 years,3916.0,Yes,No,No,No physical activity or exercise in last 30 days,Consumed fruit one or more times per day,Consumed vegetables less than one time per day,No,Yes,No,Fair,29.0,30.0,Yes,Female,Age 60 to 64,College 4 years or more (College graduate),"Less than $75,000"
1,No,No,No,Had cholesterol checked in past 5 years,1822.0,No,No,No,Had physical activity or exercise,Consumed fruit less than one time per day,Consumed vegetables one or more times per day,No,Yes,No,Good,0.0,0.0,No,Female,Age 50 to 54,College 1 year to 3 years (Some college or tec...,"$75,000 or more"
2,No,No,No,Did not have cholesterol checked in past 5 years,2746.0,Yes,No,No,No physical activity or exercise in last 30 days,Consumed fruit less than one time per day,Consumed vegetables one or more times per day,Yes,Yes,No,Good,2.0,3.0,Yes,Female,Age 55 to 59,College 4 years or more (College graduate),"$75,000 or more"
3,No,No,Yes,Had cholesterol checked in past 5 years,2197.0,No,No,No,Had physical activity or exercise,Consumed fruit less than one time per day,Consumed vegetables one or more times per day,No,Yes,No,Very good,0.0,2.0,No,Female,Age 60 to 64,Grade 12 or GED (High school graduate),"Less than $75,000"
4,No,Yes,No,Had cholesterol checked in past 5 years,3594.0,Yes,No,No,No physical activity or exercise in last 30 days,Consumed fruit less than one time per day,Consumed vegetables one or more times per day,No,Yes,No,Good,2.0,10.0,No,Male,Age 65 to 69,College 4 years or more (College graduate),"Less than $50,000"

In [8]:
# drop the incomplete data
brfss = brfss.dropna()
brfss.shape

(308056, 22)

In [9]:
#remove data type 'Yes, but female told only during pregnancy'
brfss = brfss[brfss.Diabetes_012 != 'Yes, but female told only during pregnancy']

#change 'No' to 0, 'Yes' to 2, 'No, pre-diabetes or borderline diabetes' to 1
brfss['Diabetes_012'] = brfss['Diabetes_012'].replace({'No':0,'No, pre-diabetes or borderline diabetes':1, 'Yes':2})
brfss.Diabetes_012.unique()

array([0, 2, 1])

In [10]:
brfss.shape

(305395, 22)

In [11]:
# this is just to find out the categorie types from the raw data of 'HighBP'
# HighBP = pd.Categorical(brfss['HighBP'])
# HighBP

['Yes', 'No', 'No', 'No', 'Yes', ..., 'Yes', 'No', 'Yes', 'Yes', 'No']
Length: 305395
Categories (2, object): ['No', 'Yes']

In [12]:
# HighBP
brfss['HighBP'] = brfss['HighBP'].replace({'No':0, 'Yes':1})
brfss.HighBP.unique()
brfss.shape

(305395, 22)

In [13]:
#HighChol
# replace value from string to integer
brfss['HighChol'] = brfss['HighChol'].replace({'No':0, 'Yes':1})

#remove duplicate data
brfss.HighChol.unique()

array([1, 0])

In [14]:
# CholCheck
brfss['CholCheck'] = brfss['CholCheck'].replace({'Did not have cholesterol checked in past 5 years':0,'Had cholesterol checked in past 5 years':1})
brfss.CholCheck.unique()

array([1, 0])

In [15]:
#remove CholCheck = 0 but highchol = 1 - didn't do cholesterol check in 5 years but have high cholesterol,no that reliable
brfss = brfss[~((brfss['CholCheck'] == 0) & (brfss['HighChol'] != 0))]

In [16]:
# BMI = pd.Categorical(brfss['BMI'])
# BMI

[3916.0, 1822.0, 2746.0, 2197.0, 3594.0, ..., 2663.0, 2263.0, 2539.0, 2695.0, 2613.0]
Length: 302800
Categories (3447, float64): [1211.0, 1225.0, 1232.0, 1242.0, ..., 8715.0, 8729.0, 8942.0, 9145.0]

In [17]:
# BMI
brfss['BMI'] = brfss['BMI'].div(100).round(0)
brfss.BMI.unique()

array([39., 18., 27., 22., 36., 40., 30., 28., 23., 31., 29., 32., 24.,
       41., 34., 43., 25., 37., 21., 20., 35., 33., 42., 26., 46., 44.,
       19., 17., 38., 53., 16., 54., 45., 60., 59., 64., 49., 47., 55.,
       50., 48., 15., 66., 58., 51., 52., 14., 62., 67., 57., 63., 68.,
       61., 56., 70., 65., 13., 75., 76., 73., 12., 74., 80., 85., 69.,
       72., 71., 78., 84., 79., 83., 86., 89., 77., 87., 82., 81., 91.])

In [18]:
# Smoker = pd.Categorical(brfss['Smoker'])
# Smoker

['Yes', 'No', 'Yes', 'No', 'Yes', ..., 'No', 'No', 'No', 'No', 'No']
Length: 302800
Categories (2, object): ['No', 'Yes']

In [19]:
# Smoker
brfss['Smoker'] = brfss['Smoker'].replace({'No':0, 'Yes':1})
brfss.Smoker.unique()

array([1, 0])

In [20]:
# Stroke = pd.Categorical(brfss['Stroke'])
# Stroke

['No', 'No', 'No', 'No', 'No', ..., 'No', 'No', 'No', 'No', 'No']
Length: 302800
Categories (2, object): ['No', 'Yes']

In [21]:
# Stroke
brfss['Stroke'] = brfss['Stroke'].replace({'No':0, 'Yes':1})
brfss.Stroke.unique()

array([0, 1])

In [22]:
# HeartDiseaseorAttack
brfss['HeartDiseaseorAttack'] = brfss['HeartDiseaseorAttack'].replace({'No':0, 'Yes':1})
brfss.HeartDiseaseorAttack.unique()

array([0, 1])

In [23]:
# PhysActivity
brfss['PhysActivity'] = brfss['PhysActivity'].replace({'No physical activity or exercise in last 30 days':0, 'Had physical activity or exercise':1})
brfss.PhysActivity.unique()

array([0, 1])

In [24]:
# Fruits
brfss['Fruits'] = brfss['Fruits'].replace({'Consumed fruit less than one time per day':0, 'Consumed fruit one or more times per day':1})
brfss.Fruits.unique()

array([1, 0])

In [25]:
# Veggies
brfss['Veggies'] = brfss['Veggies'].replace({'Consumed vegetables less than one time per day':0, 'Consumed vegetables one or more times per day':1})
brfss.Veggies.unique()

array([0, 1])

In [26]:
# HvyAlcoholConsump
brfss['HvyAlcoholConsump'] = brfss['HvyAlcoholConsump'].replace({'No':0, 'Yes':1})
brfss.HvyAlcoholConsump.unique()

array([0, 1])

In [27]:
# AnyHealthcare
brfss['AnyHealthcare'] = brfss['AnyHealthcare'].replace({'No':0, 'Yes':1})
brfss.AnyHealthcare.unique()

array([1, 0])

In [28]:
# NoDocbcCost
brfss['NoDocbcCost'] = brfss['NoDocbcCost'].replace({'No':0, 'Yes':1})
brfss.NoDocbcCost.unique()

array([0, 1])

In [29]:
# GenHlth
brfss['GenHlth'] = brfss['GenHlth'].replace({'Excellent':1, 'Very good':2, 'Good':3, 'Fair':4,'Poor':5,})
brfss.GenHlth.unique()

array([4, 3, 2, 1, 5])

In [30]:
# MentHlth = pd.Categorical(brfss['MentHlth'])
# MentHlth

[29.0, 0.0, 2.0, 0.0, 2.0, ..., 2.0, 0.0, 30.0, 15.0, 20.0]
Length: 302800
Categories (31, float64): [0.0, 1.0, 2.0, 3.0, ..., 27.0, 28.0, 29.0, 30.0]

In [31]:
# PhysHlth = pd.Categorical(brfss['PhysHlth'])
# PhysHlth

[30.0, 0.0, 3.0, 2.0, 10.0, ..., 0.0, 0.0, 0.0, 14.0, 15.0]
Length: 302800
Categories (31, float64): [0.0, 1.0, 2.0, 3.0, ..., 27.0, 28.0, 29.0, 30.0]

In [32]:
# DiffWalk = pd.Categorical(brfss['DiffWalk'])
# DiffWalk

['Yes', 'No', 'Yes', 'No', 'No', ..., 'No', 'No', 'No', 'Yes', 'No']
Length: 302800
Categories (2, object): ['No', 'Yes']

In [33]:
# DiffWalk
brfss['DiffWalk'] = brfss['DiffWalk'].replace({'No':0, 'Yes':1})
brfss.DiffWalk.unique()

array([1, 0])

In [34]:
# Sex
brfss['Sex'] = brfss['Sex'].replace({'Female':0, 'Male':1})
brfss.Sex.unique()

array([0, 1])

In [35]:
# Age
brfss['Age'] = brfss['Age'].replace({'Age 18 to 24':1, 'Age 25 to 29':2, 'Age 30 to 34':3, 'Age 35 to 39':4, 'Age 40 to 44':5, 'Age 45 to 49':6, 'Age 50 to 54':7, 'Age 55 to 59':8, 'Age 60 to 64':9, 'Age 65 to 69':10, 'Age 70 to 74':11, 'Age 75 to 79':12, 'Age 80 or older':13})
brfss.Age.unique()

array([ 9,  7,  8, 10,  6, 11, 12,  5,  3,  4,  1, 13,  2])

In [36]:
# Education = pd.Categorical(brfss['Education'])
# Education

['College 4 years or more (College graduate)', 'College 1 year to 3 years (Some college or te..., 'College 4 years or more (College graduate)', 'Grade 12 or GED (High school graduate)', 'College 4 years or more (College graduate)', ..., 'College 4 years or more (College graduate)', 'Grade 12 or GED (High school graduate)', 'College 1 year to 3 years (Some college or te..., 'Grade 12 or GED (High school graduate)', 'College 1 year to 3 years (Some college or te...]
Length: 302800
Categories (6, object): ['College 1 year to 3 years (Some college or te..., 'College 4 years or more (College graduate)', 'Grade 12 or GED (High school graduate)', 'Grades 1 through 8 (Elementary)', 'Grades 9 though 11 (Some high school)', 'Never attended school or only kindergarten']

In [37]:
# Education
brfss['Education'] = brfss['Education'].replace({'Never attended school or only kindergarten':1, 'Grades 1 through 8 (Elementary)':2, 'Grades 9 though 11 (Some high school)':3, 'Grade 12 or GED (High school graduate)':4, 'College 1 year to 3 years (Some college or technical school)':5, 'College 4 years or more (College graduate)':6})
brfss.Education.unique()

array([6, 5, 4, 3, 2, 1])

In [38]:
# Income = pd.Categorical(brfss['Income'])
# Income

['Less than $75,000', '$75,000 or more', '$75,000 or more', 'Less than $75,000', 'Less than $50,000', ..., 'Less than $20,000', 'Less than $15,000', 'Less than $10,000', 'Less than $15,000', 'Less than $15,000']
Length: 302800
Categories (8, object): ['$75,000 or more', 'Less than $10,000', 'Less than $15,000', 'Less than $20,000', 'Less than $25,000', 'Less than $35,000', 'Less than $50,000', 'Less than $75,000']

In [39]:
# Income
brfss['Income'] = brfss['Income'].replace({'Less than $10,000':1, 'Less than $15,000':2, 'Less than $20,000':3, 'Less than $25,000':4, 'Less than $35,000':5, 'Less than $50,000':6, 'Less than $75,000':7, '$75,000 or more':8})
brfss.Income.unique()

array([7, 8, 6, 4, 1, 5, 2, 3])

In [40]:
brfss.shape

(302800, 22)

In [41]:
brfss.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,39.0,1,0,0,0,1,0,0,1,0,4,29.0,30.0,1,0,9,6,7
1,0,0,0,1,18.0,0,0,0,1,0,1,0,1,0,3,0.0,0.0,0,0,7,5,8
2,0,0,0,0,27.0,1,0,0,0,0,1,1,1,0,3,2.0,3.0,1,0,8,6,8
3,0,0,1,1,22.0,0,0,0,1,0,1,0,1,0,2,0.0,2.0,0,0,9,4,7
4,0,1,0,1,36.0,1,0,0,0,0,1,0,1,0,3,2.0,10.0,0,1,10,6,6

In [42]:
brfss['BMI'] = pd.to_numeric(brfss['BMI'], downcast="integer")

In [43]:
brfss['MentHlth'] = pd.to_numeric(brfss['MentHlth'], downcast="integer")

In [44]:
brfss['PhysHlth'] = pd.to_numeric(brfss['PhysHlth'], downcast="integer")

In [45]:
brfss.groupby(['Diabetes_012']).size()

Diabetes_012
0    255031
1      5587
2     42182
dtype: int64

In [46]:
# Generate the csv for prcessed diabetes data of 2013
# brfss.to_csv('diabetes_012_health_indicators_BRFSS2013.csv', sep=",", index=False)

In [46]:
# load the prcessed diabetes data of 2015
brfss_2015 = pd.read_csv('./diabetes_012_health_indicators_BRFSS2015.csv',encoding='ISO-8859-1')

In [47]:
brfss_2015.shape

(253680, 22)

In [77]:
# combine the two years(2013,2015) data together
brfss1315 = brfss_2015.append(brfss, ignore_index = True)

In [78]:
brfss1315.shape

(556480, 22)

In [79]:
# 0 - non-diabetic ,1 - pre-diabetic, 2 - diabetic
brfss1315.groupby(['Diabetes_012']).size()

Diabetes_012
0    468734
1     10218
2     77528
dtype: int64

# crerate diabetes 01 balance dataset
# combine 0 - Non-diabetic and 1 - Pre-diabetic

In [80]:
brfss_binary = brfss1315

In [81]:
# remove didn't do cholcheck in 5 years but have highchol
brfss_binary = brfss_binary[~((brfss_binary['CholCheck'] == 0) & (brfss_binary['HighChol'] != 0))]
brfss_binary.shape

(554499, 22)

In [82]:
#combine non-diabetic & pre-diabetic as 0 , change diabetic from 2 to 1
brfss_binary['Diabetes_012'] = brfss_binary['Diabetes_012'].replace({1:0})
brfss_binary['Diabetes_012'] = brfss_binary['Diabetes_012'].replace({2:1})

brfss_binary = brfss_binary.rename(columns = {'Diabetes_012': 'Diabetes_01'})
brfss_binary.Diabetes_01.unique()

/home/xavior/anaconda3/envs/project36/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/xavior/anaconda3/envs/project36/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

array([0, 1])

In [83]:
brfss_binary.groupby(['Diabetes_01']).size()

Diabetes_01
0    477106
1     77393
dtype: int64

In [84]:
# Get the 1s
is1 = brfss_binary['Diabetes_01'] == 1
brfss_1 = brfss_binary[is1]

#Get the 0s
is0 = brfss_binary['Diabetes_01'] == 0
brfss_0 = brfss_binary[is0]

In [85]:
# Randomly pick up the same number of 1s from 0s
brfss_0_rand1 = brfss_0.take(np.random.permutation(len(brfss_0))[:77393])

In [86]:
# combine into a balance dataset
brfss_5050 = brfss_0_rand1.append(brfss_1, ignore_index = True)

In [87]:
brfss_5050.groupby(['Diabetes_01']).size()

Diabetes_01
0    77393
1    77393
dtype: int64

In [88]:
brfss_5050.tail()

,Diabetes_01,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
154781,1,1,1,1,32,1,0,0,0,0,1,0,1,0,5,30,30,1,0,11,3,1
154782,1,1,0,1,30,1,1,0,0,1,0,0,1,0,4,4,15,1,0,10,2,2
154783,1,1,1,1,23,0,0,0,0,0,1,0,1,0,4,0,0,0,0,11,4,2
154784,1,0,1,1,25,0,0,0,0,0,1,0,1,0,3,30,0,0,0,10,5,1
154785,1,1,1,1,27,0,0,1,0,1,1,0,1,0,4,15,14,1,0,8,4,2

In [90]:
# Generate out the csv
brfss_5050.to_csv('diabetes_binary.csv', sep=",", index=False)

# create diabetes 012 balance dataset

In [101]:
# remove didn't do cholcheck in 5 years but have highchol
brfss1315 = brfss1315[~((brfss1315['CholCheck'] == 0) & (brfss1315['HighChol'] != 0))]
brfss1315.shape

(554499, 22)

In [102]:
# remove highBP=1, highchol=1,smoker=1,both mental and physical health problem days >25 ,but diabetes_012 != 2
brfss1315 = brfss1315[~((brfss1315['HighBP'] == 1) & (brfss1315['HighChol'] == 1) & (brfss1315['Smoker'] == 1) & (brfss1315['MentHlth'] >= 25) & (brfss1315['PhysHlth'] >= 25) & (brfss1315['Diabetes_012'] != 2))]

In [103]:
# highBP=0, highchol=0,smoker=0,both mental and physical health problem days <= 5,but diabetes_012 != 0
brfss1315 = brfss1315[~((brfss1315['HighBP'] == 0) & (brfss1315['HighChol'] == 0) & (brfss1315['Smoker'] == 0) & (brfss1315['MentHlth'] <= 5) & (brfss1315['PhysHlth'] <= 5) & (brfss1315['Diabetes_012'] != 0))]

In [104]:
brfss1315.shape

(548107, 22)

In [105]:
is1 = brfss1315['Diabetes_012'] == 1
brfss1 = brfss1315[is1]
brfss1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
64,1,1,1,1,27,0,0,0,1,1,1,0,1,1,4,30,30,1,0,10,4,3
81,1,1,1,1,33,0,0,0,0,0,1,0,1,0,3,3,0,0,1,7,4,7
193,1,1,1,1,34,0,0,0,0,0,1,0,1,0,2,0,0,0,0,7,4,8
275,1,1,1,1,32,1,1,0,1,0,1,0,1,0,5,0,30,1,1,8,5,7
360,1,1,1,1,26,1,0,0,0,0,1,0,0,1,3,30,15,1,0,6,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556385,1,1,0,1,29,0,0,0,1,0,1,0,1,0,2,0,0,0,1,11,4,2
556388,1,0,1,1,29,0,0,1,1,1,1,0,1,0,5,0,0,0,1,11,5,2
556427,1,0,0,1,35,0,0,0,0,1,1,0,1,0,3,30,0,0,1,2,4,5
556436,1,1,1,1,26,0,0,0,0,0,1,0,1,0,4,30,3,1,0,9,4,3
556446,1,1,1,1,29,0,0,0,0,1,1,0,1,0,4,0,0,0,0,10,4,2

In [106]:
is0 = brfss1315['Diabetes_012'] == 0
brfss0 = brfss1315[is0]
brfss0

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,40,1,0,0,0,0,1,0,1,0,5,18,15,1,0,9,4,3
1,0,0,0,0,25,1,0,0,1,0,0,0,0,1,3,0,0,0,0,7,6,1
2,0,1,1,1,28,0,0,0,0,1,0,0,1,1,5,30,30,1,0,9,4,8
3,0,1,0,1,27,0,0,0,1,1,1,0,1,0,2,0,0,0,0,11,3,6
4,0,1,1,1,24,0,0,0,1,1,1,0,1,0,2,3,0,0,0,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556472,0,0,0,1,30,0,0,0,1,0,0,0,1,0,3,0,0,0,0,5,6,3
556473,0,0,0,0,27,0,0,0,1,1,1,0,0,0,2,0,0,0,1,6,5,4
556474,0,0,0,1,32,0,0,0,0,0,1,0,1,0,3,0,0,0,0,2,6,4
556475,0,0,0,1,27,0,0,0,0,1,1,0,1,0,4,2,0,0,0,10,6,3
556479,0,0,0,1,26,0,0,0,1,1,1,0,1,1,4,20,15,0,0,4,5,2

In [108]:
is2 = brfss1315['Diabetes_012'] == 2
brfss2 = brfss1315[is2]
brfss2

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
8,2,1,1,1,30,1,0,1,0,1,1,0,1,0,5,30,30,1,0,9,5,1
10,2,0,0,1,25,1,0,0,1,1,1,0,1,0,3,0,0,0,1,13,6,8
13,2,1,1,1,28,0,0,0,0,0,1,0,1,0,4,0,0,1,0,11,4,6
17,2,0,0,1,23,1,0,0,1,0,0,0,1,0,2,0,0,0,1,7,5,6
23,2,1,0,1,27,0,0,0,1,1,1,0,1,0,1,0,0,0,0,13,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556468,2,1,1,1,32,1,0,0,0,0,1,0,1,0,5,30,30,1,0,11,3,1
556469,2,1,0,1,30,1,1,0,0,1,0,0,1,0,4,4,15,1,0,10,2,2
556476,2,1,1,1,23,0,0,0,0,0,1,0,1,0,4,0,0,0,0,11,4,2
556477,2,0,1,1,25,0,0,0,0,0,1,0,1,0,3,30,0,0,0,10,5,1
556478,2,1,1,1,27,0,0,1,0,1,1,0,1,0,4,15,14,1,0,8,4,2

In [109]:
brfss0_rand1 = brfss0.take(np.random.permutation(len(brfss0))[:9226])

In [110]:
brfss2_rand1 = brfss2.take(np.random.permutation(len(brfss2))[:9226])

In [111]:
brfss_01 = brfss0_rand1.append(brfss1, ignore_index = True)

In [112]:
brfss_012 = brfss_01.append(brfss2_rand1, ignore_index = True)

In [113]:
brfss_012

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,22,1,0,0,1,1,0,0,1,0,3,5,0,0,0,13,4,6
1,0,0,1,1,38,1,0,0,0,0,0,0,1,0,4,0,30,1,1,11,4,7
2,0,0,0,1,24,0,0,0,1,1,1,0,1,0,2,0,0,0,1,9,6,8
3,0,1,1,1,29,1,0,0,1,1,1,0,1,0,2,0,0,0,1,8,6,8
4,0,0,0,1,27,1,0,0,1,0,0,0,1,0,4,2,0,0,0,1,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27673,2,1,0,1,31,1,0,0,0,1,1,0,1,0,3,0,0,1,1,12,3,3
27674,2,1,1,1,25,0,0,0,1,0,1,0,1,0,3,0,0,0,0,13,5,6
27675,2,1,1,1,35,1,0,1,0,1,1,0,1,0,4,25,25,1,0,8,5,6
27676,2,1,1,1,37,1,0,0,1,1,1,0,1,0,4,15,15,1,1,11,4,5
27677,2,1,1,1,28,1,0,0,1,1,1,0,1,0,3,1,10,0,0,10,5,4

In [114]:
brfss_012.groupby(['Diabetes_012']).size()

Diabetes_012
0    9226
1    9226
2    9226
dtype: int64

In [115]:
brfss_012.to_csv('diabetes_012_13_15.csv', sep=",", index=False)

In [116]:
brfss_012.groupby(['Diabetes_012']).size()

Diabetes_012
0    9226
1    9226
2    9226
dtype: int64