# Group 10 project - Create a multinomial naive bayes model

In [1]:
# !pip install scikit-learn==0.23.1

Requirement already satisfied: scikit-learn==0.23.1 in /home/xavior/anaconda3/envs/project36/lib/python3.6/site-packages (0.23.1)
Requirement already satisfied: scipy>=0.19.1 in /home/xavior/anaconda3/envs/project36/lib/python3.6/site-packages (from scikit-learn==0.23.1) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /home/xavior/anaconda3/envs/project36/lib/python3.6/site-packages (from scikit-learn==0.23.1) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/xavior/anaconda3/envs/project36/lib/python3.6/site-packages (from scikit-learn==0.23.1) (3.1.0)
Requirement already satisfied: numpy>=1.13.3 in /home/xavior/anaconda3/envs/project36/lib/python3.6/site-packages (from scikit-learn==0.23.1) (1.19.2)

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import MultinomialNB

In [5]:
# Loading the dataset
dbt_data = pd.read_csv('./diabetes_binary.csv')

In [6]:
# Create scaler
scaler = MinMaxScaler(feature_range=(0, 1))

In [7]:
dbt_data['Diabetes_01']

0         0
1         0
2         0
3         0
4         0
         ..
154781    1
154782    1
154783    1
154784    1
154785    1
Name: Diabetes_01, Length: 154786, dtype: int64

In [8]:
# categorical
HighBP = pd.Categorical(dbt_data['HighBP'])
HighChol = pd.Categorical(dbt_data['HighChol'])
CholCheck = pd.Categorical(dbt_data['CholCheck'])
Smoker = pd.Categorical(dbt_data['Smoker'])
Stroke = pd.Categorical(dbt_data['Stroke'])
HeartDiseaseorAttack = pd.Categorical(dbt_data['HeartDiseaseorAttack'])
PhysActivity = pd.Categorical(dbt_data['PhysActivity'])
Fruits = pd.Categorical(dbt_data['Fruits'])
Veggies = pd.Categorical(dbt_data['Veggies'])
HvyAlcoholConsump = pd.Categorical(dbt_data['HvyAlcoholConsump'])
AnyHealthcare = pd.Categorical(dbt_data['AnyHealthcare'])
NoDocbcCost = pd.Categorical(dbt_data['NoDocbcCost'])
# GenHlth = pd.Categorical(dbt_data['GenHlth'])
DiffWalk = pd.Categorical(dbt_data['DiffWalk'])
Sex = pd.Categorical(dbt_data['Sex'])
# Age = pd.Categorical(dbt_data['Age'])
# Education = pd.Categorical(dbt_data['Education'])
# Income = pd.Categorical(dbt_data['Income'])
Diabetes_01 = pd.Categorical(dbt_data['Diabetes_01'])

#scaling
dbt_data[['BMI','MentHlth','PhysHlth','Age','GenHlth','Education','Income']] = scaler.fit_transform(dbt_data[['BMI','MentHlth','PhysHlth','Age','GenHlth','Education','Income']])

dbt_data['HighBP'] = HighBP
dbt_data['HighChol'] = HighChol
dbt_data['CholCheck'] = CholCheck
dbt_data['Smoker'] = Smoker
dbt_data['Stroke'] = Stroke
dbt_data['HeartDiseaseorAttack'] = HeartDiseaseorAttack
dbt_data['PhysActivity'] = PhysActivity
dbt_data['Fruits'] = Fruits
dbt_data['Veggies'] = Veggies
dbt_data['HvyAlcoholConsump'] = HvyAlcoholConsump
dbt_data['AnyHealthcare'] = AnyHealthcare
dbt_data['NoDocbcCost'] = NoDocbcCost
# dbt_data['GenHlth'] = GenHlth
dbt_data['DiffWalk'] = DiffWalk
dbt_data['Sex'] = Sex
# dbt_data['Age'] = Age
# dbt_data['Education'] = Education
# dbt_data['Income'] = Income
dbt_data['Diabetes_01'] = Diabetes_01

# X = dbt_data.drop(['Diabetes_01'], axis=1)
X = dbt_data.drop(['Diabetes_01','CholCheck','AnyHealthcare','NoDocbcCost',
                   'GenHlth','Education','Income'], axis=1)
X

,HighBP,HighChol,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,MentHlth,PhysHlth,DiffWalk,Sex,Age
0,0,0,0.116279,1,0,0,1,1,1,0,0.133333,0.000000,0,0,0.416667
1,0,0,0.058140,1,0,0,1,1,1,0,0.000000,0.066667,0,0,0.666667
2,0,0,0.151163,1,0,0,0,1,1,1,1.000000,0.133333,0,1,0.333333
3,0,0,0.162791,1,0,1,1,1,1,0,0.000000,0.000000,0,1,1.000000
4,0,1,0.255814,0,0,0,1,1,0,0,0.000000,0.033333,0,0,0.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154781,1,1,0.232558,1,0,0,0,0,1,0,1.000000,1.000000,1,0,0.833333
154782,1,0,0.209302,1,1,0,0,1,0,0,0.133333,0.500000,1,0,0.750000
154783,1,1,0.127907,0,0,0,0,0,1,0,0.000000,0.000000,0,0,0.833333
154784,0,1,0.151163,0,0,0,0,0,1,0,1.000000,0.000000,0,0,0.750000
154785,1,1,0.174419,0,0,1,0,1,1,0,0.500000,0.466667,1,0,0.583333

In [9]:
Y_classification = dbt_data.Diabetes_01

In [10]:
# Split train/test 
X_train, X_test, y_train, y_test = train_test_split(X, Y_classification, test_size=1 / 5, random_state=1,
                                                    stratify=Y_classification)
# print(X_train.shape)
# print(X_test.shape)

In [11]:
NaiveBayesModel = MultinomialNB()
NaiveBayesModel.fit(X_train, y_train)

# print('Score in training set: {:.3f}'.format(NaiveBayesModel.score(X_train, y_train)))
# print('Score in test set: {:.3f}'.format(NaiveBayesModel.score(X_test,y_test)))

MultinomialNB()

In [12]:
def pred(data):
    prediction = NaiveBayesModel.predict(data)
    return prediction

In [2]:
import pickle

In [3]:
dbtmodel_pkl = open('dbtmodel.pkl','wb')

In [13]:
pickle.dump(NaiveBayesModel,dbtmodel_pkl)

In [14]:
dbtmodel_pkl.close()